name: Apply
on:
  push:
    branches: [ main ]  
  workflow_dispatch:

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    env: 
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_1 }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_1 }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - id: init
        name: Terraform Init
        run: |
          terraform init
    