# This is a basic workflow to help you get started with Actions. This could be a meaningful name which will be displayed in the Actions tab of the repository.
name: Plan

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "main" branch
  push: 
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  terraform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository 
      - name: Checkout
        uses: actions/checkout@v3

      # Runs a single command using the runners shell. This is just for testing purposes.
      - name: Run a one-line script
        run: echo Hello, world!
  
      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init
        env: 
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        
      # Terraform format
      - name: Terraform Format
        run: terraform fmt -check -recursive

      # Terraform plan
      - name: Terraform Plan
        run: terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      # On push to main, build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
